title: This is a Test Blog   or is it?
author: Washington University
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I am going to document things

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
